COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.PERIODE IS '#NAVN PERIODE #INNHOLD Statistikk periode, YYYYMM';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.STATISTIKK_FOM IS '#NAVN STATISTIKK_FOM #INNHOLD Start dato for statistikk periode':
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.STATISTIKK_TOM IS '#NAVN STATISTIKK_TOM #INNHOLD Slutt dato for statistikk periode';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FK_PERSON1_OMSORGSPERSON IS '#NAVN FK_PERSON1_OMSORGSPERSON #INNHOLD Fk_person1 til mottaker';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FK_PERSON1_PLEIETRENGENDE IS '#NAVN FK_PERSON1_PLEIETRENGENDE #INNHOLD DVH sin identifikator for den pleietrengede sin FNR.';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.RELASJON_TIL_OMSORGSPERSON IS '#NAVN RELASJON_TIL_OMSORGSPERSON #INNHOLD Relasjonen mottakeren har til pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.YRKESSTATUS IS '#NAVN YRKESSTATUS #INNHOLD En kode kode som representerer arbeidsforholds stil en pleiepenger mottaker har. f.eks, "AT", "SN" osv';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ORGNR IS '#NAVN ORGNR #INNHOLD En kode som representerer organisasjonen en pleiepenger mottaker jobber i';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.KOMMUNE_NR IS '#NAVN KOMMUNE_NR #INNHOLD Bostedskommunenr for mottaker';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.BYDEL_KOMMUNE_NR IS '#NAVN BYDEL_KOMMUNE_NR #INNHOLD Bydel kommunenr. for mottaker/omsorgsperson';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FK_DIM_DIAGNOSE IS '#NAVN FK_DIM_DIAGNOSE #INNHOLD Fremmednøkkel til DIM_DIAGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.DIAGNOSE_TYPE IS '#NAVN DIAGNOSE_TYPE #INNHOLD Diagnose type';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.DIAGNOSE_KODE IS '#NAVN DIAGNOSE_KODE #INNHOLD Diagnose kode. Dersom flere diagnoser vilkårlig hvilken som blir valgt. Alle diagnoser i FAM_PP_DIAGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.DIAGNOSE_BESKRIVELSE IS '#NAVN DIAGNOSE_BESKRIVELSE #INNHOLD En beskrivelse til diagnosen (diagnose koden)';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_KODE IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_BESK IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_GRUPPE_KODE IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_GRUPPE_BESK IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_KAPITTEL_KODE IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ICPC2_KAPITTEL_BESK IS '#NAVN #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.IDENTDATO IS '#NAVN INNHOLD';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.VEDTAKS_DATO IS '#NAVN VEDTAKS_DATO #INNHOLD Vedtaksdato for aktuelt Behandlings_id';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ANVIST_FOM IS '#NAVN INNHOLD';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ANVIST_TOM IS '#NAVN INNHOLD';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ANVIST_DATO IS '#NAVN INNHOLD';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.YTELSE_TYPE IS '#NAVN YTELSE_TYPE #INNHOLD Ytelsetype PSB:Pleiepenger sykt barn, PPN:Pleiepenger nære relasjoner, OMP:Omsorgspenger.';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.INNGR IS 
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.BRUTTO_BEREGNINGSGRUNNLAG IS '#NAVN BRUTTO_BEREGNINGSGRUNNLAG #INNHOLD Brutto årlig inntektsgrunnlag. Ikke begrtenset til 6G';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FORBRUKTE_DAGER IS '#NAVN FORBRUKTE_DAGER #INNHOLD Forbrukte dager';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FORBRUKTE_DAGER_VEKTET IS '#NAVN FORBRUKTE_DAGER_VEKTET #INNHOLD Forbrukte dager vektet i andel av den totale';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.UTTAKSGRAD IS '#NAVN UTTAKSGRAD #INNHOLD Uttaksgrad i prosent, ref. FAM_PP_PERIODER';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.DAGSATS IS '#NAVN DAGSATS #INNHOLD Dagsats for aktuelt arbeidsforhold, redusert med i henhold til uttaksgrad, ref. FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.DAGSATS_TOTAL IS '#NAVN DAGSATS_TOTAL #INNHOLD Total dagsats uavhengig av arbeidsforhold';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.BELOP IS '#NAVN BELOP #INNHOLD Beløp utbetalt.Fra UR når KILDESYSTEM=PP_VEDTAK_UR.';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.ANTALL_DAGER IS '#NAVN ANTALL_DAGER #INNHOLD Antall dager i aktuell periode. Lørdag og Søndag telles ikke.';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.UTBETALINGSGRAD IS '#NAVN UTBETALINGSGRAD #INNHOLD Utbetalingsgrader. Ref. FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.PLEIEBEHOV IS '#NAVN PLEIEBEHOV #INNHOLD Den pleietrengdende sitt pleiebehov i prosent. 100 eller 200. Ref. FAM_PP_PERIODER';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.OPPGITT_TILSYN IS '#NAVN OPPGITT_TILSYN #INNHOLD Oppgitt tilsyn i timer per dag, ISO 8601 format. Eneste verdi benyttet PT7H30M. Ref. FAM_PP_PERIODER';
COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.SOKERS_TAPTE_TIMER IS '#NAVN SOKERS_TAPTE_TIMER #INNHOLD Søkers tapte timer i ISO 8601 format, f.eks PT4H17';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.SOKERS_TAPTE_ARBEIDSTID IS '#NAVN SOKERS_TAPTE_ARBEIDSTID #INNHOLD Søkers tapte arbeidstid i prosent';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.UTFALL IS '#NAVN UTFALL #INNHOLD Utfall på aktuell pleieperiode, ref. FAM_PP_PERIODER. Mulig verdi: IKKE OPPFYLT, OPPFYLT';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.MAX_VEDTAKSDATO IS '#NAVN MAX_VEDTAKSDATO #INNHOLD Siste mulige vedtaksdato benyttet for månedskjøring når KILDESSYTEM=PP_VEDTAK. Benyttes kun når KILDESSYTEM=PP_VEDTAK.';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.BEHANDLINGS_ID IS '#NAVN BEHANDLINGS_ID #INNHOLD Behandlings_id for vedtaket i fagsystemet.';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.SAKSNUMMER IS '#NAVN SAKSNUMMER #INNHOLD Eksternt saksnummer for vedtaket i fagsystemet (FAM_PP_FAGSAK).';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FODSEL_AAR_MOTTAKER IS '#NAVN FODSEL_AAR_MOTTAKER #INNHOLD Fødselesår til når mottakeren ble født';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FODSEL_MND_MOTTAKER IS '#NAVN FODSEL_MND_MOTTAKER #INNHOLD Fødselesmåned til når mottakeren ble født';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FODSEL_AAR_PLEIETRENGENDE IS '#NAVN FODSEL_AAR_PLEIETRENGENDE #INNHOLD Fødselesår til når pleietrengende ble født';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FODSEL_MND_PLEIETRENGENDE IS '#NAVN FODSEL_MND_PLEIETRENGENDE #INNHOLD Fødselesmåned til når pleietrengende ble født';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.KJONN_MOTTAKER IS '#NAVN KJONN_MOTTAKER #INNHOLD Mottakerens kjønn';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.KJONN_PLEIETRENGENDE IS '#NAVN KJONN_PLEIETRENGENDE #INNHOLD Kjønn på pleietrengende';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.FK_DIM_PERSON_PLEIETRENGENDE IS '#NAVN FK_DIM_PERSON_PLEIETRENGENDE #INNHOLD Fremmednøkkel til pleietrengende (barn) i dim_person tabellen';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.AARSAK_1 IS '#NAVN AARSAK_1 #INNHOLD En årsak til at en bestemt periode blir oppfylt eller ikke oppfylt';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.AARSAK_2 IS '#NAVN AARSAK_2 #INNHOLD Mulig en årsaken til at en bestemt periode blir oppfylt eller ikke oppfylt';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.NATTEVAAK IS '#NAVN NATTEVAAK #INNHOLD Oppfylt eller ikke oppfylt flagg, den sier om vilkårene for "nattvåken" er oppfylt eller ikke';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.BEREDSKAP IS '#NAVN BEREDSKAP #INNHOLD Oppfylt eller ikke oppfylt flagg, den sier om vilkårene for "må stå klar til å hjelpe/gi tilsyn" er oppfylt eller ikke';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.GMT_OVERSE_ETABLERT_TILSYN_AARSAK IS '#NAVN GMT_OVERSE_ETABLERT_TILSYN_AARSAK #INNHOLD';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.GMT_ANDRE_SOKERS_TILSYN IS '#NAVN GMT_ANDRE_SOKERS_TILSYN #INNHOLD Prosentandel tilsyn den andre forelderen/en annen person enn mottaker har med pleietrengende';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.GMT_ETABLERT_TILSYN IS '#NAVN GMT_ETABLERT_TILSYN #INNHOLD Prosentandel av det etablerte tilsynet barnet allerede har (barnehage, skole osv)';

COMMENT ON COLUMN DVH_FAM_PP.FAK_PP_STONAD_UR.GMT_TILGJENGELIG_FOR_SOKER IS '#NAVN GMT_TILGJENGELIG_FOR_SOKER #INNHOLD Prosentandel tilsyn søker (mottaker) har med pleietrengende.';
