COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.PK_VILKAAR_DETALJERT_UTFALL IS '#NAVN PK_VILKAAR_DETALJERT_UTFALL #INNHOLD Primærnøkkel er en unik ID for hver rad, autogenerert fra dvh_fampp_kafka.hibernate_sequence.nextval';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.LASTET_DATO IS '#NAVN LASTET_DATO #INNHOLD Tidsstempel som angir når en rad ble lagt til i tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.FK_PP_PERIODE_INNGANGSVILKAAR IS '#NAVN FK_PP_PERIODE_INNGANGSVILKAAR #INNHOLD Fremmednøkkel til fam_pp_periode_inngangsvilkaar tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.GJELDER_KRAVSTILLER IS '#NAVN GJELDER_KRAVSTILLER #INNHOLD Hvem som sendte omsorgspenger kravet Brukeren selv eller arbeidsgiveren';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.GJELDER_AKTIVITET_TYPE IS '#NAVN GJELDER_AKTIVITET_TYPE #INNHOLD En kode kode som representerer arbeidsforholdets stil en omsorgspenger mottaker f.eks er "AT", "SN" osv ';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.GJELDER_ORGANISASJONSNUMMER IS '#NAVN GJELDER_ORGANISASJONSNUMMER #INNHOLD En kode som representerer organisasjonen en omsorgspenger mottaker jobber for';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.GJELDER_AKTOR_ID IS '#NAVN GJELDER_AKTOR_ID #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.GJELDER_ARBEIDSFORHOLD_ID IS '#NAVN GJELDER_ARBEIDSFORHOLD_ID #INNHOLD En kode som forteller hva slags type jobb/aktivitet mottakeren har';
COMMENT ON COLUMN DVH_FAM_PP.FAM_VILKAAR_DETALJER_UTFALL.DET_UTFALL IS '#NAVN DET_UTFALL #INNHOLD Oppfylt eller ikke oppfylt flagg som forteller om arbeidsvilkårene for å mottak omsorgspenger oppfylt eller ikke';
