COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.PK_PP_PERIODER IS '#NAVN PK_PP_PERIODER #INNHOLD Primærnøkkel er en unik ID for hver rad, autogenerert fra dvh_fampp_kafka.hibernate_sequence.nextval';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.BRUTTO_BEREGNINGSGRUNNLAG IS '#NAVN BRUTTO_BEREGNINGSGRUNNLAG #INNHOLD Grunnlaget som brukes for å beregne pleiepengene. Beløpet er før skatt';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.DATO_FOM IS '#NAVN DATO_FOM #INNHOLD Datoen pleiepengerutbetalingen gjelder fra';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.DATO_TOM IS '#NAVN DATO_TOM #INNHOLD Datoen pleiepengerutbetalingen gjelder til';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.GMT_ETABLERT_TILSYN IS '#NAVN GMT_ETABLERT_TILSYN #INNHOLD Prosentandel av det etablerte tilsynet barnet allerede har (barnehage, skole osv)';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.GMT_TILGJENGELIG_FOR_SOKER IS '#NAVN GMT_TILGJENGELIG_FOR_SOKER #INNHOLD Prosentandel tilsyn søker (mottaker) har med pleietrengende.';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.PLEIEBEHOV IS '#NAVN PLEIEBEHOV #INNHOLD Hvor mye pleie pleietrengende har behov for 0-100%. i noen tilfeller kan pleietrengende har behov for 200% tilsyn';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.SOKERS_TAPTE_ARBEIDSTID IS '#NAVN SOKERS_TAPTE_ARBEIDSTID #INNHOLD Prosentandel arbeidstimer søkeren taper for å gi tilsyn til den pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.UTTAKSGRAD IS '#NAVN UTTAKSGRAD #INNHOLD Hvor stor andel av full arbeidstid søkeren tar fri fra jobb for å gi tilsyn til den pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.FK_PP_FAGSAK IS '#NAVN FK_PP_FAGSAK #INNHOLD Fremmednøkkel til fagsak tabellen (vedtaket)';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.LASTET_DATO IS '#NAVN LASTET_DATO #INNHOLD Tidsstempel som angir når en rad ble lagt til i tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.TOTAL_UTBETALINGSGRAD IS '#NAVN TOTAL_UTBETALINGSGRAD #INNHOLD Den samlede andelen av full inntekt som faktisk blir utbetalt';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.TOTAL_UTBETALINGSGRAD_FRA_UTTAK IS '#NAVN TOTAL_UTBETALINGSGRAD_FRA_UTTAK #INNHOLD Hvor mye mottakeren får utbetalt basert på det uttaket mottakeren har registrert';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.TOTAL_UTBETALINGSGRAD_ETTER_REDUKSJON_VED_TILKOMMET_INNTEKT IS '#NAVN TOTAL_UTBETALINGSGRAD_ETTER_REDUKSJON_VED_TILKOMMET_INNTEKT #INNHOLD Hvor stor del av full lønn mottakeren får utbetalt etter at pleiepenger er redusert på grunn av ekstra inntekter';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.BEREDSKAP IS '#NAVN BEREDSKAP #INNHOLD Oppfylt eller ikke oppfylt flagg, den sier om vilkårene for "må stå klar til å hjelpe/gi tilsyn" er oppfylt eller ikke';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.GMT_ANDRE_SOKERS_TILSYN IS '#NAVN GMT_ANDRE_SOKERS_TILSYN #INNHOLD Prosentandel tilsyn den andre forelderen/en annen person enn mottaker har med pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.GMT_OVERSE_ETABLERT_TILSYN_AARSAK IS '#NAVN GMT_OVERSE_ETABLERT_TILSYN_AARSAK #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.NATTEVAAK IS '#NAVN NATTEVAAK #INNHOLD  Oppfylt eller ikke oppfylt flagg, den sier om vilkårene for "nattvåken" er oppfylt eller ikke';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.OPPGITT_TILSYN IS '#NAVN OPPGITT_TILSYN #INNHOLD Antall timer søkeren oppgir at den bruker på tilsyn med den pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.SOKERS_TAPTE_TIMER IS '#NAVN SOKERS_TAPTE_TIMER #INNHOLD Antall arbeidstimer søkeren taper for å gi tilsyn til den pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_PERIODER.UTFALL IS '#NAVN UTFALL #INNHOLD Oppfylt eller ikke oppfylt om pleiepenger er innvilget for enbestemt periode';