COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BEHANDLINGS_ID IS '#NAVN BEHANDLINGS_ID #INNHOLD Behandlings_id for vedtaket i fagsystemet.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FORRIGE_BEHANDLINGS_ID IS '#NAVN FORRIGE_BEHANDLINGS_ID #INNHOLD Forrige behandlings_id for aktuelt vedtak i fagsystemet.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_PERSON1_MOTTAKER IS '#NAVN FK_PERSON1_MOTTAKER #INNHOLD DVH sin identifikator for FNR, mottaker(omsorgsperson) av ytelsen.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_PERSON1_PLEIETRENGENDE IS '#NAVN FK_PERSON1_PLEIETRENGENDE #INNHOLD DVH sin identifikator for den pleietrengede sin FNR.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.SAKSNUMMER IS '#NAVN SAKSNUMMER #INNHOLD Eksternt saksnummer for vedtaket i fagsystemet (FAM_PP_FAGSAK).'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTBETALINGSREFERANSE IS '#NAVN UTBETALINGSREFERANSE #INNHOLD Utbetalingsreferanse fra FAM_FP_FAGSAK, koblingsøkkel mot behandlings_id i UR.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.YTELSE_TYPE IS '#NAVN YTELSE_TYPE #INNHOLD Ytelsetype PSB:Pleiepenger sykt barn, PPN:Pleiepenger nære relasjoner, OMP:Omsorgspenger.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.VEDTAKS_DATO IS '#NAVN VEDTAKS_DATO #INNHOLD Vedtaksdato for aktuelt Behandlings_id'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ANTALL_BEHANDLINGS_ID IS '#NAVN ANTALL_BEHANDLINGS_ID #INNHOLD Antall behandligs_id registrert. Benyttes kun når KILDESSYTEM=PP_VEDTAK. Bør '
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.MAX_VEDTAKSDATO IS '#NAVN MAX_VEDTAKSDATO #INNHOLD Siste mulige vedtaksdato benyttet for månedskjøring når KILDESSYTEM=PP_VEDTAK.Benyttes kun når KILDESSYTEM=PP_VEDTAK.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.MIN_DATO_FOM IS '#NAVN MIN_DATO_FOM #INNHOLD Datoen pleiepengerutbetalingen gjelder fra'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.MAX_DATO_TOM IS '#NAVN MAX_DATO_TOM #INNHOLD Datoen pleiepengerutbetalingen gjelder til'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BRUTTO_BEREGNINGSGRUNNLAG IS '#NAVN BRUTTO_BEREGNINGSGRUNNLAG #INNHOLD Brutto årlig inntektsgrunnlag. Ikke begrtenset til 6G'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.DAGSATS_TOTAL IS '#NAVN DAGSATS_TOTAL #INNHOLD Total dagsats uavhengig av arbeidsforhold'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.OPPGITT_TILSYN IS '#NAVN OPPGITT_TILSYN #INNHOLD Oppgitt tilsyn i timer per dag, ISO 8601 format. Eneste verdi benyttet PT7H30M. Ref. FAM_PP_PERIODER'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.PLEIEBEHOV IS '#NAVN PLEIEBEHOV #INNHOLD Den pleietrengdende sitt pleiebehov i prosent. 100 eller 200. Ref. FAM_PP_PERIODER'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.SOKERS_TAPTE_TIMER IS '#NAVN SOKERS_TAPTE_TIMER #INNHOLD Søkers tapte timer i ISO 8601 format, f.eks PT4H17'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.SOKERS_TAPTE_ARBEIDSTID IS '#NAVN SOKERS_TAPTE_ARBEIDSTID #INNHOLD Søkers tapte arbeidstid i prosent'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTFALL IS '#NAVN UTFALL #INNHOLD Utfall på aktuell pleieperiode, ref. FAM_PP_PERIODER. Mulig verdi: IKKE OPPFYLT, OPPFYLT'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTTAKSGRAD IS '#NAVN UTTAKSGRAD #INNHOLD Uttaksgrad i prosent, ref. FAM_PP_PERIODER'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTBET_FOM IS '#NAVN UTBET_FOM #INNHOLD F.O.M. dato for utbetalt stønadsperiode.Fra UR når KILDESYSTEM=PP_VEDTAK_UR'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTBET_TOM IS '#NAVN UTBET_TOM #INNHOLD T.O.M. dato for utbetalt stønadsperiode.Fra UR når KILDESYSTEM=PP_VEDTAK_UR'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.DAGSATS IS '#NAVN DAGSATS #INNHOLD Dagsats for aktuelt arbeidsforhold, redusert med i henhold til uttaksgrad, ref. FAM_PP_PERIODE_UTBET_GRADER'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ANTALL_DAGER IS '#NAVN ANTALL_DAGER #INNHOLD Antall dager i aktuell periode. Lørdag og Søndag telles ikke.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BELOP IS '#NAVN BELOP #INNHOLD Beløp utbetalt.Fra UR når KILDESYSTEM=PP_VEDTAK_UR.'
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ARBEIDSFORHOLD_AKTORID IS '#NAVN ARBEIDSFORHOLD_AKTORID #INNHOLD Arebidsforhold aktørid'

COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ARBEIDSFORHOLD_ID IS '#NAVN ARBEIDSFORHOLD_ID #INNHOLD  En ID som representerer type arbeidsforhold en pleiepenger mottaker har';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ARBEIDSFORHOLD_ORGNR IS '#NAVN ARBEIDSFORHOLD_ORGNR #INNHOLD En kode som representerer organisasjonen en pleiepenger mottaker jobber i';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ARBEIDSFORHOLD_TYPE IS '#NAVN ARBEIDSFORHOLD_TYPE #INNHOLD En kode kode som representerer arbeidsforholds stil en pleiepenger mottaker har. f.eks, "AT", "SN" osv';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.NORMAL_ARBEIDSTID IS '#NAVN NORMAL_ARBEIDSTID #INNHOLD Normal arbeidstid, ISO 8601 format. f.eks. PT6M. Ref.FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FAKTISK_ARBEIDSTID IS '#NAVN FAKTISK_ARBEIDSTID #INNHOLD Faktisk arbeidstid, ISO 8601 format. f.eks. PT6M. Ref.FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UTBETALINGSGRAD IS '#NAVN UTBETALINGSGRAD #INNHOLD Utbetalingsgrader. Ref. FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BRUKER_ER_MOTTAKER IS '#NAVN BRUKER_ER_MOTTAKER #INNHOLD 1=direkteutbetaling. 0=Refusjon. Ref.FAM_PP_PERIODE_UTBET_GRADER';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.DIAGNOSE_KODE IS '#NAVN DIAGNOSE_KODE #INNHOLD Diagnose kode. Dersom flere diagnoser vilkårlig hvilken som blir valgt. Alle diagnoser i FAM_PP_DIAGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.DIAGNOSE_TYPE IS '#NAVN DIAGNOSE_TYPE #INNHOLD Diagnose type';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FORBRUKTE_DAGER IS '#NAVN FORBRUKTE_DAGER #INNHOLD Forbrukte dager';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.PK_PP_STONAD IS '#NAVN PK_PP_STONAD #INNHOLD Primær nøkkel for tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.GYLDIG_FLAGG IS '#NAVN GYLDIG_FLAGG #INNHOLD GYLDIG_FLAGG=1 for verifiserte/gyldige transaksjoner';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.STATISTIKK_FOM IS '#NAVN STATISTIKK_FOM #INNHOLD Start dato for statistikk periode';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.STATISTIKK_TOM IS '#NAVN STATISTIKK_TOM #INNHOLD Slutt dato for statistikk periode';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.PERIODE IS '#NAVN PERIODE #INNHOLD Statistikk periode, YYYYMM';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.KILDESYSTEM IS '#NAVN KILDESYSTEM #INNHOLD Kildesystem: PP_VEDTAK eller PP_VEDTAK_UR. Kun vedtaksinformasjon ';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.LASTET_DATO IS '#NAVN LASTET_DATO #INNHOLD Lastet dato til DVH';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.VEKT IS '#NAVN VEKT #INNHOLD Andel av utbetaling for aktuell arbeidgiver i forhold til total utbetaling';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FORBRUKTE_DAGER_VEKTET IS '#NAVN FORBRUKTE_DAGER_VEKTET #INNHOLD Forbrukte dager vektet i andel av den totale';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_DIM_PERSON IS '#NAVN FK_DIM_PERSON #INNHOLD Fremmednøkkel til DIM_PERSON for mottaker';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_DIM_GEOGRAFI IS '#NAVN FK_DIM_GEOGRAFI #INNHOLD Fremmednøkkel til DIM_GEOGRAFI for mottaker';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BOSTED_KOMMUNE_NR IS '#NAVN BOSTED_KOMMUNE_NR #INNHOLD Bostedskommunenr. for mottaker';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.BYDEL_KOMMUNE_NR IS '#NAVN BYDEL_KOMMUNE_NR #INNHOLD Bydel kommunenr. for mottaker/omsorgsperson';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.ANTALL_DIAGNOSE IS '#NAVN ANTALL_DIAGNOSE #INNHOLD Antall Diagnoser, alle diagnose i tabellen FAM_PP_DIAGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_PP_DIAGNOSE IS '#NAVN FK_PP_DIAGNOSE #INNHOLD Fremmednøkkel til DIM_DAIGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.RELASJON IS '#NAVN RELASJON #INNHOLD Relasjon mellom omsorgsperson og pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_PP_RELASJONER IS '#NAVN FK_PP_RELASJONER #INNHOLD Fremmednøkkel til FAM_PP_RELASJONER';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_UR_UTBETALING IS '#NAVN FK_UR_UTBETALING #INNHOLD Fremmednøkkel transaksjoner i UR';

COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_PP_PERIODER IS '#NAVN FK_PP_PERIODER #INNHOLD Fremmednøkkel til fam_bb_perioder tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_DIM_DIAGNOSE IS '#NAVN FK_DIM_DIAGNOSE #INNHOLD Fremmednøkkel til DIM_DIAGNOSE';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FODSEL_AAR_MOTTAKER IS '#NAVN FODSEL_AAR_MOTTAKER #INNHOLD Fødselesår til når mottakeren ble født';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FODSEL_AAR_PLEIETRENGENDE IS '#NAVN FODSEL_AAR_PLEIETRENGENDE #INNHOLD Fødselesår til når pleietrengende ble født';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FODSEL_MND_MOTTAKER IS '#NAVN FODSEL_MND_MOTTAKER #INNHOLD Fødselesmåned til når mottakeren ble født';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FODSEL_MND_PLEIETRENGENDE IS '#NAVN FODSEL_MND_PLEIETRENGENDE #INNHOLD Fødselesmåned til når pleietrengende ble født';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.HOVEDKONTONR IS '#NAVN HOVEDKONTONR #INNHOLD Kontonummer til pleiepenger i UR systemet';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.OPPDATERT_DATO IS '#NAVN OPPDATERT_DATO #INNHOLD Datoen til når rekorden ble siste oppdatert i tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.UNDERKONTONR IS '#NAVN UNDERKONTONR #INNHOLD Underkonto nummer';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.FK_DIM_PERSON_PLEIETRENGENDE IS '#NAVN FK_DIM_PERSON_PLEIETRENGENDE #INNHOLD Fremmednøkkel til pleietrengende (barn) i dim_person tabellen';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.KJONN_OMSORGSPERSON IS '#NAVN KJONN_OMSORGSPERSON #INNHOLD Kjønn på mottakeren';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.KJONN_PLEIETRENGENDE IS '#NAVN KJONN_PLEIETRENGENDE #INNHOLD Kjønn på pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.MOTTAKER_FS IS '#NAVN MOTTAKER_FS #INNHOLD ';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.AKTIVITET_STATUS IS '#NAVN AKTIVITET_STATUS #INNHOLD En kode som forteller hva slags type jobb/aktivitet mottakere har';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.TYPE_MOTTAKER IS '#NAVN TYPE_MOTTAKER #INNHOLD Om det er ORG eller brukeren selv';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.KUN_KRONISK_SYKT_BARN_OVER12 IS '#NAVN KUN_KRONISK_SYKT_BARN_OVER12 #INNHOLD Flagg (0/1) som angir om et barn er over 12 år og har kronisk sykdom; 1 = ja, 0 = nei';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.AARSAK_1 IS '#NAVN AARSAK_1 #INNHOLD En årsak til at en bestemt periode blir oppfylt eller ikke oppfylt';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.GMT_ANDRE_SOKERS_TILSYN IS '#NAVN GMT_ANDRE_SOKERS_TILSYN #INNHOLD Prosentandel tilsyn den andre forelderen/en annen person enn mottaker har med pleietrengende';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.GMT_ETABLERT_TILSYN IS '#NAVN GMT_ETABLERT_TILSYN #INNHOLD Prosentandel av det etablerte tilsynet barnet allerede har (barnehage, skole osv)';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.GMT_TILGJENGELIG_FOR_SOKER IS '#NAVN GMT_TILGJENGELIG_FOR_SOKER #INNHOLD Prosentandel tilsyn søker (mottaker) har med pleietrengende.';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.AARSAK_2 IS '#NAVN AARSAK_2 #INNHOLD Mulig en årsaken til at en bestemt periode blir oppfylt eller ikke oppfylt';
COMMENT ON COLUMN DVH_FAM_PP.FAM_PP_STONAD.POSTERINGSDATO_UR IS '#NAVN POSTERINGSDATO_UR #INNHOLD Posteringsdato i UR';