version: 2

sources:
  - name: arena_stonad
    description: ''
    schema: dt_p
    tables:
      - name: dim_f_stonad_omraade
        description: 'inneholder infromasjon om stonader, som bl.a stonad_kode, stonad_navn osv'
      - name: dim_maalgruppe_type
        description: 'inneholder infromasjon om målgrupper, som bl.a maalgruppe_kode, maalgruppe_navn osv'
      - name: fak_stonad
        descripion: 'inneholder informasjon om stonad til brukere. inneholder fk_person1, postert_belop, aar, inntekt osv'
      - name: dim_vedtak_postering
        description: ''
      - name: dim_kjonn
        description: 'inneholder informasjon om kjonn mann, kvinne, ukjent'
      - name: dim_alder
        description: 'inneholder informasjon om alderen til brukere'
      - name: dim_geografi
        description: 'inneholder geografiske informasjon, bla fylke_navn, kommune_nr osv '
      - name: dim_person
        description: 'inneholder informasjon om brukere, bla kjonn, fodeland, statsborgerskap osv'
      - name: dim_vilkaar_type
        description: ''
      - name: fak_arena_sak_vedtak
        description: ''
      - name: fak_vedtak_fakta
        description: ''
      - name: fak_vilkaar_vurdering
        description: ''

  - name: dt_person_arena
    schema: dt_person
    tables:
      - name: dim_person_kontaktinfo
        description: 'inneholder informasjon om brukere, bla navn, telefon_mobil, k67_flagg osv, '
      - name: dvh_person_ident_off_id_ikke_skjermet
        description: 'inneholder informasjon om personer som er ikke skjemet, bl.a fk_person1, off_id'
      - name: DIM_PERSON

  - name: kode_verk
    schema: dt_kodeverk
    tables:
     - name: dim_alder
     - name: dim_tid

  - name: fam_pp
    schema: dvh_fam_pp
    tables:
      - name: fam_pp_meta_data
        description: 'inneholder meta_data for PP, OMP, PPN'
      - name: fam_pp_fagsak
        description: 'inneholder vedtaks informasjon'
      - name: fam_pp_diagnose
        description: 'inneholder diagnose informasjon'
      - name: fam_pp_perioder
        description: 'Inneholder infromasjon om perioder'
      - name: fam_pp_periode_utbet_grader
        description: 'Inneholder infromasjon om utbetalinger'

  - name: dt_kodeverk
    description: 'Datavarehus dimensjons data'
    schema: dt_kodeverk
    tables:
      - name: dim_tid
        description: 'Inneholder infromasjon om tid'

  - name: ur
    schema: dvh_ur
    tables:
      - name: fak_ur_utbetaling
        description: 'Et view som inneholder utbetalingers detaljier'
      - name: DIM_KONTO_UR



